FROM ubuntu:18.04
LABEL maintainer = "dormarble dormarble <gudfla0814@gmail.com>"
RUN apt-get update
RUN apt-get install openjdk-8-jdk -y

RUN mkdir -p /var/www
ADD ./ /

RUN ./gradlew bootjar
WORKDIR /build/libs

EXPOSE 8080
CMD java -jar server.jar
